# Generated by Django 5.2.7 on 2025-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_nome',
            field=models.CharField(default='Pinto', max_length=30),
            preserve_default=False,
        ),
    ]
