# Generated by Django 5.2.7 on 2025-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criado_em',
            new_name='criado',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Geral', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Marca desconhecida', max_length=50),
            preserve_default=False,
        ),
    ]
