# Generated by Django 5.2.7 on 2025-10-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('loja', '0002_rename_criado_em_produto_criado_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='criado_em',
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
    ]
